### ISSUE TITLE
Keep the letter case during the substitution. 

### ISSUE THREAD

**Issue by DmitryMK** [jaflo/umlauter#1]
[Firefox 60/Umlauter 0.0.10]
Hello Jaflo, thank you for the extension, it helps a lot. Word "Uemlaut" is automatically transformed to "ümlaut". I think it will be beneficial if the letter case can be kept, i.e. "Ue -> Ü, ue -> ü"?

**Comment by jaflo** [comment]
This is indeed an issue. I made a fix in 38f30f92cf0b4107f186954b0cf5de82f235270b and will publish extension v. 0.0.11 to the stores. Thank you for your bug report!
